version: 2.1

parameters:
  func:
    description: The operation to perform on the given numbers
    type: enum
    enum:
      - "ADD"
      - "SUB"
      - "MUL"
      - "DIV"
  numA:
    type: integer
    description: "The first number"
  numB:
    type: integer
    description: "The second number"

jobs:
  math_operation:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Perform Math Operation
          command: |
            if [[ "$CIRCLECI" ]]; then
              if [[ "${func}" == "ADD" ]]; then
                result=$(expr ${numA} + ${numB})
              elif [[ "${func}" == "SUB" ]]; then
                result=$(expr ${numA} - ${numB})
              elif [[ "${func}" == "MUL" ]]; then
                result=$(expr ${numA} \* ${numB})
              elif [[ "${func}" == "DIV" ]]; then
                result=$(expr ${numA} / ${numB})
              else
                echo "Invalid operation specified."
                exit 1
              fi
              echo "Result: ${result}"
              touch /tmp/ADD_RESULT.txt
              echo "$result" > /tmp/ADD_RESULT.txt
            fi
